### PR TITLE
[SystemUpdate]: handle Openstore app updates

### PR DESCRIPTION
**Pull request by mardy**
Change the client API URL to point at the OpenStore, and update the JSON
parsing to match the Openstore's format.
Remove all the code related to the SSO and token download, and remove
the now unneeded dependency on libUbuntuOneAuth. We can bring it back
later, should we ever find the need.

The Openstore support can be improved once the two following bugs are
fixed:
- https://github.com/UbuntuOpenStore/openstore-meta/issues/156
- https://github.com/UbuntuOpenStore/openstore-meta/issues/157

### CODE REVIEW

**Comment by mardy** [comment]
Is it correct to target `vivid-dev`, or should I rather target `vivid`?

**Comment by mariogrip** [comment]
Awesome! Thanks!

I moved the branch to vivid_-_dev due to new build infrastructure (ppa does not build vivid anymore)
https://github.com/ubports/build-tools for more info

http://ci.ubports.com/blue/organizations/jenkins/ubports%2Fsystem-settings/detail/vivid_-_dev/2/pipeline

(merge done for build to trigger, discussion can still continue)

**Comment by Flohack74** [comment]
Another new branch? Which one is now the one we use for ci builds? My translations all go into vivid it seems.

**Comment by mariogrip** [comment]
vivid - goes into images
vivid_-_* - test branches, does not effect anything (but need the (vivid_-_ to depend on the vivid branch)

so vivid_-_test does not effect our rootfs

This way people can try this branch adding vivid_-_test to there apt sources
explained here: https://github.com/ubports/build-tools

**Comment by mardy** [comment]
@mariogrip what's the difference between `vivid` and `vivid_-_dev` branches? Is it that `vivid` == stable channel, and `vivid_-_dev` == devel channel?

**Pull request merged**
