### PR TITLE
Move Apn Choose and Editor to new PageHeader and pagestack api

### LINKED ISSUE #535: [xenial] hammerhead: cannot add or modify APN from mobile-network's settings.
BUG-REPORT

- Device: hammerhead
- Channel: 16.04 devel
- Build: r304

### Steps to reproduce

Occurs when you need to modify or add an APN to set up your internet connection.

### Expected behavior

Be able to add a new or modify an existing one. 

### Actual behavior

There is no  button to add (+) and no button to save a modified one.

### Logfiles and additional information

Until this bug is not fixed, i will be not able to use my mobile-internet-connection while i am around.

### PR DESCRIPTION
**Pull request by mariogrip**
This fixes https://github.com/ubports/ubuntu-touch/issues/535

### CODE REVIEW

**Comment by Flohack74** [comment]
Was this device-specific?

**Review by NeoTheThird — APPROVED** [review]
Lgtm

**Comment by mariogrip** [comment]
@Flohack74 no, was on all devices where they was missing the save/addnew button

**Comment by Flohack74** [comment]
Ok then I remove hammerhead from the related bug.

**Pull request merged**
