### PR TITLE
Small fix in it-po

### PR DESCRIPTION
**Pull request by Aury88**
correct a typo and refined some strings translations

### CODE REVIEW

**Comment by Aury88** [comment]
@sverzegnassi can you help me? I don't understand why a simple change in the string translation has done this mess in the checks.

**Comment by Flohack74** [comment]
Sorry but po PRs will not be accepted. Use https://translate.ubports.com for that, otherwise we get merge conflicts. Thank You!

**Comment by Aury88** [comment]
Hi @Flohack74,

how I find the 146, the 2603, the 4249 and the 4255 lines in weblates?....have I to check one by one every string in every 823 tabs/positions or is there  a way to search a specific string/line?

**Comment by Flohack74** [comment]
Try https://translate.ubports.com/projects/ubports/system-settings/it/#search

**Comment by Aury88** [comment]
thank you very much! I did not see it...I have to have my eyes checked xD

**Pull request closed without merging**
