### PR TITLE
Openstore

### PR DESCRIPTION
**Pull request by mardy**
Support latest openstore API.

I'm targeting the "vivid-dev" branch because I want this to end up in the "devel" channel. Please correct me if my understanding is wrong.

### CODE REVIEW

**Review by bhdouglass — CHANGES_REQUESTED** [review]
This PR doesn't seem to take into account the OpenStore's system of revisions. Ignoring that has the potential for causing major trouble as version numbers are left solely to the developers and revisions are what we use to track what needs to be updated (see the OpenStore app's code for an example). If OpenStore app updates are to be processed through the system settings this needs to be addressed to avoid two widely different approaches to updates.

**Comment by mardy** [comment]
@bhdouglass I can do that. I'm not 100% convinced that it's the right thing to do, but given that the openstore app (and also the snap store) work in that way, maybe I have to adapt to the new world order ;-)

**Comment by mardy** [comment]
@bhdouglass I've investigated the issue, and it seems to be much more complex than what I expected. The main issue is that click has no concept of revisions: there doesn't seem to be a way to get the revision of the installed click packages. I guess (but please correct me if I'm wrong) that the openstore app remembers the revision of a click when it downloads it, but it will be unable to update a click package that was preinstalled in the image.

Edit: it seems that the openstore lists even preinstalled and sideloaded clicks, but it crashes once I click on any of them.

**Comment by mardy** [comment]
So, I don't think I can do the changes you requested until the click tool gets the notion of revision; until that happens, our best bet to figure out whether a package needs an update is the version number.

**Comment by bhdouglass** [comment]
@mardy I don't think the issue of this being the correct solution or not is what needs to be discussed here. How we are doing it is with revision so in order to do updates without pitfalls (pitfalls that we have solved with revisions) and not have a different behavior from the OpenStore app, you should use the revisions. If you feel that revisions are the wrong approach and have some edge cases that we are not covering please feel free to open an issue on the OpenStore for discussion.

The OpenStore app doesn't store revision numbers nor does the click tool need to care about revision. We check for updates by sending the installed apps version to the api and get back a list of the revision for the current version (one version equals one revision and they are unique versions) and the current revision in the OpenStore (if you want to see this in action just check out the OpenStore app's code). We are already using revision numbers in the OpenStore app so version numbers are not the "best bet" for the system settings.

**Comment by mardy** [comment]
@bhdouglass I see, that makes sense. But if the packages returned by the api/v2/apps endpoint are the latest revisions available for each app, then I think I can continue using that endpoint, and just fix the client side: at the moment it's comparing the version numbers and proposing the update only if the remote one compare higher (according to dpkg versioning rules), while I should propose the update whenever the version is simply different.
Do you see some problems with this approach?

Edit: I see, the problem is probably with sideloaded apps: on the client side there's no way to determine which app has been sideloaded, so we need to check with the server whether the currently installed version is known to it (if it is, the server also knows its revision, so can tell whether there's a newer version available out there).

**Comment by bhdouglass** [comment]
@mardy sounds like you answered your own question :smile:

**Comment by mardy** [comment]
I've updated the branch, to use the openstore revisions. I'm not sure how to handle sideloaded apps: at the moment, this branch is ignoring them, but maybe for sideloaded apps it would be better to check the package version in order to decide whether to propose an update?

Anyway, this is a minor issue which mostly affects only app developers; we can change it later.

**Comment by bhdouglass** [comment]
@mardy ignoring them seems fine for an initial release.

I realized that the `api/v2/apps` endpoint that you added didn't include the paging data that the OpenStore app and website expect, so I've pushed a fix for that, you'll probably need to adjust your code.

**Comment by mardy** [comment]
Thanks @bhdouglass , branch updated :-)

**Comment by mardy** [comment]
Ping! Can I merge this now?

**Comment by bhdouglass** [comment]
Are there instructions for how I can install this and test it?

**Comment by mardy** [comment]
@bhdouglass The easiest way that I'm aware of, is to checkout this branch and build it with crossbuilder (you can find some info about it at https://wiki.ubports.com/wiki/Developing-system-software): this will build the code and install it on the device.
Then you just need to start the system settings and see if it finds the available updates (to test this, I usually upload a new version of a dummy package I've in the store).

**Comment by mardy** [comment]
Please review this, I really want to have it in the next OTA :-)

**Comment by bhdouglass** [comment]
My apologies, I haven't had a chance to test this out as I've been super busy. Is it possible to get this into a dev release channel? That would simplify my test it.

**Comment by NeoTheThird** [comment]
Let's just merge it for now, if everything breaks terribly, we'll see.

**Comment by mardy** [comment]
Thanks @NeoTheThird ! I guess this means that @bhdouglass can test the upcoming "devel" image (or fetch the .deb from [Jenkins](https://ci.ubports.com/view/vivid/job/ubports/job/system-settings/job/vivid-dev/lastSuccessfulBuild/artifact/libsystemsettings1_0.5+ubports+0%7E20171215094036.13%7E1.gbpe29151_armhf.deb)) and report his feedback here.
Then I can propose a MP against the `vivid` branch to have it land in the stable images (or is the unstable channel automatically promoted to stable as the OTA is released?).

**Comment by NeoTheThird** [comment]
Oh right, it's in vivid-dev, it needs to go in vivid to be built into devel. Vivid-dev was originally set up to build debs into a special ppa for QA, but canonical disabled all vivid ppas, so that's not happening any more.

**Pull request merged**
