### PR TITLE
WIP: Change display order of 'Language & Text' settings

### PR DESCRIPTION
**Pull request by mateosalta**
reorganize and try to sort out different dividers
photo_2020-07-21_10-32-37

### CODE REVIEW

**Comment by mateosalta** [comment]
So the order of items reorganized follows this logic:
- Language items (language selection, spelling, suggestions)
- Text options, changed to checkbox (auto cap, punctuation)
- Keyboard and osk options 


screenshot20200721_161420832
screenshot20200721_161314262

**Comment by mateosalta** [comment]
need to fix word wrap/ size on checkmark items

**Comment by dobey** [comment]
Is this a draft/WIP branch?

**Comment by mateosalta** [comment]
@dobey oh, yes. I forget to mark as, the main thing I ran into that was a blocker is that the listitem I used for the checkbox did not word wrap.

**Comment by UniversalSuperBox** [comment]
Hello,

Thank you for your contribution to system-settings. We have now moved this repository to GitLab to take advantage of better issue tracking and CI capabilities.

Things are going to be a little crazy for this repository between now and the release of Ubuntu Touch based on 20.04, but here's what you need to know:

* This PR was re-created automatically as a GitLab MR at https://gitlab.com/ubports/core/lomiri-system-settings/-/merge_requests/243. Unfortunately, if you would like to make changes to this MR on GitLab, you will need to fork the new repository, push your new changes, and create a new MR.
* You will probably want to work on the `ubports/xenial` branch when you are creating MRs. The `main` branch is only built for Ubuntu Touch based on 20.04, so you will be unable to test your changes for now.

If you have any questions, please comment on the MR that GitLab created for you. We'll try our best to answer.

**Pull request closed without merging**
