### PR TITLE
App icon as svg (updated from Yaru). Add Splashscreen image

### PR DESCRIPTION
**Pull request by cibersheep**

### CODE REVIEW

**Comment by cibersheep** [comment]
App Icon Before / After

imatge
imatge

Splash Before / After

imatge

imatge

**Comment by cibersheep** [comment]
@Flohack74 it could be really cool to have this splash in for OTA 13 ^__^ 
What do you think?

**Review by Flohack74 — APPROVED** [review]

**Comment by Flohack74** [comment]
Sure lets do it ^^

**Comment by cibersheep** [comment]
I love you ^__^

**Pull request merged**
