### PR TITLE
Added toggle to display battery percentage in the top panel

### PR DESCRIPTION
**Pull request by kugiigi**
Sample screenshot:
screenshot20200531_170403659

### CODE REVIEW

**Comment by mateosalta** [comment]
Perhaps you could just have it one line - since checkboxes are descriptive actions
 "Show battery percentage next to indicator"

**Comment by kugiigi** [comment]
> Perhaps you could just have it one line - since checkboxes are descriptive actions
> "Show battery percentage next to indicator"

I'm really bad with words so I'm open for suggestions. But in this case, my reasoning is that I want to make it possible to add more settings if ever in the future. And I don't feel good putting long labels on checkboxes/toggles, not sure why 😅

**Comment by mateosalta** [comment]
I don't think there will be multiple in this category for battery soon, 

 for some guidance from the good-old design docs:
https://docs.google.com/document/d/1Pd3ORoNlH7SAU9zkxKg3-0VdxhWXwcgS-bsPteCQhiw/edit#

maybe more like "Show percentage in indicators" - since user is in 'battery' settings allready

**Comment by Flohack74** [comment]
Some comments, I would replace the battery symbol with the percentage. Since indiactor space is scarce, we should not waste it and keep it slim :) @cibersheep can you review that from UX perspective?
Also the little text "In the top panel" is not needed, just give a terse description for the button and people will understand

**Comment by kugiigi** [comment]
Sorry, I should have posted a screenshot of the updated one.
I removed the header and changed the label a bit.
screenshot20210321_221221904

As for the actual percentage in the indicator, personally I still want the battery icon there though it would be good if the parentheses are removed. Perhaps adding options to show icon or percentage or both? In any case, those will be done in the battery indicator :)

**Comment by Flohack74** [comment]
Why not like this, saves space. Yes the parentheses need to go in any way, takes too much space :)
grafik

**Comment by Flohack74** [comment]
Also you can still show charging state with this style.

**Comment by cibersheep** [comment]
Mmm... I think the battery icon and the percentage is too much space. Since you can pull the indicator and have it there if you need it.

I think I would go more as showing or `[\\  ]·` the battery icon or `[30%]·` text instead but not both at the same time

**Comment by kugiigi** [comment]
I think Florian's suggestion is fine and it's actually a common design for the battery indicator. In terms development, I'm not sure how simple or complicated it is to rotate icons in the indicator :sweat_smile: 

I still stand with my opinion though, I would want an option to show both. It would look weird to me showing just the percentage also, what would be displayed when charging?

In any case, I feel like this should be discussed separately. This is only for a toggle that already exist which is currently only available via UTTT :grinning:

**Comment by cibersheep** [comment]
> I still stand with my opinion though, I would want an option to show both. It would look weird to me showing just the percentage also, what would be displayed when charging?

I'm not talking to only show the percentage, more like this (don't look at the colors)

imatge

So, show the percentage in numbers or show the percentage in bars

**Comment by kugiigi** [comment]
Oh okay, sorry I did not see it that way :sweat_smile: 
My concern with that though is how readable can it be given that the icon is already small as it is now.

**Comment by mateosalta** [comment]
yeah, we at least need to remove the () brackets from these ;)

**Comment by kugiigi** [comment]
This removes the parentheses.
ubports/indicator-power#51

**Comment by UniversalSuperBox** [comment]
Hello,

Thank you for your contribution to system-settings. We have now moved this repository to GitLab to take advantage of better issue tracking and CI capabilities.

Things are going to be a little crazy for this repository between now and the release of Ubuntu Touch based on 20.04, but here's what you need to know:

* This PR was re-created automatically as a GitLab MR at https://gitlab.com/ubports/core/lomiri-system-settings/-/merge_requests/236. Unfortunately, if you would like to make changes to this MR on GitLab, you will need to fork the new repository, push your new changes, and create a new MR.
* You will probably want to work on the `ubports/xenial` branch when you are creating MRs. The `main` branch is only built for Ubuntu Touch based on 20.04, so you will be unable to test your changes for now.

If you have any questions, please comment on the MR that GitLab created for you. We'll try our best to answer.

**Pull request closed without merging**
