### PR TITLE
Remove dependency on ual.

### PR DESCRIPTION
**Pull request by z3ntu**
The dependency on ubuntu-app-launch creates a circular dependency, as
ubuntu-app-launch depends on libertine, which depends on system-settings.
Instead, we'll just build the URL and use QDesktopServices to open it.

---

I picked this commit from the bionic branch (see #82), is this change wanted on xenial?

### CODE REVIEW

**Review by peat-psuwit — APPROVED** [review]
Tested on FP2 (with Halium 7.1). Application update seems to work correctly, and recently updated apps can be launched. Did not test system image update as I have other apt repositories installed. Did not test other settings page.

**Review by mariogrip — APPROVED** [review]
LGTM :+1:

**Comment by jezek** [comment]
There is a call for testing. How do we test this, please?

**Comment by peat-psuwit** [comment]
For QA: try upgrading apps from system-settings and then launch them.

**Comment by UniversalSuperBox** [comment]
I was able to upgrade and launch Clock, OpenStore, and Calculator from system-settings.

**Comment by jezek** [comment]
Device: FP2
Image: 2020-W37

Was able to upgrade and launch Weather app from system-settings.

**Pull request merged**
