### PR TITLE
WIP: language: Add support for click language packs

### PR DESCRIPTION
**Pull request by mardy**
Experimental branch, do not merge yet.

This can be tested by making the image read-write (`sudo mount -o rw,remount /`), installing the new system-settings packages from Jenkins, then downloading a few clicks from https://ci.ubports.com/job/xenial-rootfs-minimal-armhf/24/artifact/clicks/ on the device and installing them:

    pkcon  --allow-untrusted install-local com.ubports.language-fr_20181001-27507_all.click

Then, if you open the System Settings and go to the language page, you should see that you can only choose among the languages you installed. And if you confirm the new language and reboot, everything should work as expected.

Of course, the whole point of this effort is to get a smaller rootfs: this is available from https://ci.ubports.com/job/xenial-rootfs-minimal-armhf/lastSuccessfulBuild/artifact/out/ but I haven't yet verified if it works. :-)

_______________________

TODO
====
- Include in the clicks also the keyboard prediction files (`/usr/share/maliit/plugins/com/ubuntu/lib/*`): if we include only the databases, we can probably keep the .click files architecture independent; or we need to find a way to avoid the need for the binary `.so` files
- Add a "Install more languages" button to the System Settings
- Automatically upload the language clicks to the Open Store
- Update the Ubports installer to *optionally* use the new rootfs; and if we manage to find a way to preinstall the clicks onto the rootfs, we could even make the user select the desired languages from the installer

### CODE REVIEW

**Comment by bhdouglass** [comment]
@mardy since this is marked as WIP what still needs to be done so we can merge this in?

**Comment by mardy** [comment]
@bhdouglass The last commit of this branch adds an "Install more…" button to the System Settings / Languages panel, but that button does nothing. This MR depends on https://github.com/ubports/click-reviewers-tools/pull/3, and on the language packs being supported in the open store. I haven't had time to work on Ubports lately, but hopefully that will change soon.

**Comment by dobey** [comment]
> @mardy since this is marked as WIP what still needs to be done so we can merge this in?

Is there consensus that we _should_ merge it, and continue with the idea of having language packs? IMO, it would be better if we can find some way to ship them all by default, and optimize other things out of the image which we actually don't need.

**Comment by mardy** [comment]
> Is there consensus that we _should_ merge it, and continue with the idea of having language packs? IMO, it would be better if we can find some way to ship them all by default, and optimize other things out of the image which we actually don't need.

No, there isn't a consensus yet, but I think we can reach it :-) But first, let me explain what this branch will do: for users running on a regular image (with all language data installed) nothing will change: if you look at the [`canInstallMore()`](https://github.com/ubports/system-settings/blob/11f9ae2b19170dde9d2665755dc6ee0895654cf7/plugins/language/language-plugin.cpp#L158) function, you'll see that the new button will appear only for images where language data has been installed as a click package. So, once the branch is ready, it will cause no harm.

Let's continue the discussion about whether we want the feature or not in the [forum](https://forums.ubports.com/topic/1800/language-packs-as-click-packages-call-to-arms). Sorry that I dropped off, but unfortunately the time available for Ubports comes and goes. :-)

**Comment by myii** [comment]
@mardy The CI build tests have been fixed with #105, so to get the build passing for this PR, you need to rebase on the latest changes in the `xenial` branch and then `git push -f` to trigger another CI build.

**Comment by UniversalSuperBox** [comment]
Hello,

Thank you for your contribution to system-settings. We have now moved this repository to GitLab to take advantage of better issue tracking and CI capabilities.

Things are going to be a little crazy for this repository between now and the release of Ubuntu Touch based on 20.04, but here's what you need to know:

* This PR was re-created automatically as a GitLab MR at https://gitlab.com/ubports/core/lomiri-system-settings/-/merge_requests/272. Unfortunately, if you would like to make changes to this MR on GitLab, you will need to fork the new repository, push your new changes, and create a new MR.
* You will probably want to work on the `ubports/xenial` branch when you are creating MRs. The `main` branch is only built for Ubuntu Touch based on 20.04, so you will be unable to test your changes for now.

If you have any questions, please comment on the MR that GitLab created for you. We'll try our best to answer.

**Pull request closed without merging**
