### PR TITLE
Fix app updates on non-armhf systems.

### PR DESCRIPTION
**Pull request by dobey**
Fixes the wrong architecture packages being downloaded for app updates on systems which aren't armhf.

### CODE REVIEW

**Comment by bhdouglass** [comment]
@dobey I believe we need to have this check the arch as well: https://github.com/ubports/system-settings/blob/2448cbbb6a981525b6a8dd3a9eb1fc51596f2b32/plugins/system-update/click/manager_impl.cpp#L370

**Comment by dobey** [comment]
> @dobey I believe we need to have this check the arch as well:

Hmm, maybe, but given the revision check will only have things that support the current arch, I guess it's not 100% necessary. Also, wouldn't that break arch `all` updates?

**Comment by bhdouglass** [comment]
The openstore app checks both the current arch and `all`, but it won't matter cause I'm updating the api so it fixes system settings without a change here. But this change is still needed for arm64 devices.

**Comment by mariogrip** [comment]
oh sorry! didn't see this before now so i kinda started on this on my own, so i ended up with this to support for multi arch: https://github.com/ubports/system-settings/pull/195

**Comment by UniversalSuperBox** [comment]
I believe this was superseded by https://github.com/ubports/system-settings/pull/195

**Pull request closed without merging**
