### PR TITLE
Better estimation of the speeds for types of network

### PR DESCRIPTION
**Pull request by Flohack74**

### CODE REVIEW

**Comment by Flohack74** [comment]
Also needs updated pot file, please do not merge yet...

**Review by UniversalSuperBox — CHANGES_REQUESTED** [review]
Missing update of translation sources

**Comment by Flohack74** [comment]
It´s PITA that Github does not allow turning a made PR into a draft...

**Comment by mariogrip** [comment]
humm, im not sure if I agree with this. slow, fast, faster is simpler to understand for everyone and our goal should be simplicity over complexity.

**Comment by Flohack74** [comment]
We can go for that but slow 2g fast 3g faster 4g - what comes at 5g? fasterissimo? xD

**Comment by Flohack74** [comment]
Its like they messed up refrigerator efficiency here.... They started at G or so, and A was the best class... Now they had to add A+, A++, A+++ ... I think we are at A++++ already.
The advantage of a technical fact is that its always true ;)

**Comment by UniversalSuperBox** [comment]
Well, once we have 5G we could bump each level up a notch -- since 2G will probably be gone, it can be "2g (blank), 3G: slower, 4G: fast, 5G: faster"

Iunno, I have no strong opinion either way.

**Comment by Flohack74** [comment]
Maybe just leave that classifications at all? Just write 2G..5G, people should by 2020 know what that means ^^ - just mention that 2G saves battery. And actually 2G will stay, 3G will go, as 2G is used in an unknown amount of 100.000s of embedded devices that no one can easily exchange. So if they kill 2G, they will have the companies on them which are using those kinda "pre-IoT devices"

**Comment by UniversalSuperBox** [comment]
That sounds good to me.

**Comment by Flohack74** [comment]
@UniversalSuperBox ready to merge?

**Comment by UniversalSuperBox** [comment]
Only if the pot file is updated as well

**Review by UniversalSuperBox — APPROVED** [review]

**Pull request merged**
