### PR TITLE
[SystemImage] Add option to switch between channels 

### PR DESCRIPTION
**Pull request by mariogrip**
This adds options to switch between the different channels with the same ubuntu series name (example 15.04)

### CODE REVIEW

**Comment by mariogrip** [comment]
[Dont merge yet]

**Review by Flohack74 — APPROVED** [review]
Looks OK but by jut reading the code I cant be sure 100% =)

**Review by NeoTheThird — APPROVED** [review]
Looks good, from what i can see.

**Comment by NeoTheThird** [comment]
Can this be merged? @mariogrip

**Comment by Flohack74** [comment]
Just to link the relevant issue here: https://github.com/ubports/ubports-touch/issues/73

**Pull request merged**
