### PR TITLE
pageHeader was hiding the content and added some UbuntuShapes

### LINKED ISSUE #75: [Xenial] Some elements hidden by Header
1. Open Notifications > app
2. First item «enable notifications» switch is hidden behind header
3. Flickable is bad anchored? So it doesn't flick making imposible to access the switch

imatge

### PR DESCRIPTION
**Pull request by mymike00**
fixes #75 
added UbuntuShape to app icons and resized to right dimensions

### CODE REVIEW

**Comment by mymike00** [comment]
wait a moment before merging I'll have other fixes for this evening

**Comment by cibersheep** [comment]
Oh. Do we know why it fails to build?
This fix would be cool as some of the System Settings are not accessible #91

**Comment by dobey** [comment]
> Oh. Do we know why it fails to build?
> This fix would be cool as some of the System Settings are not accessible #91

It seems lots of tests are failing or broken, perhaps by the changes here, as they were building OK before.

**Comment by cibersheep** [comment]
So, @mymike00 do you mind checking those errors and see if you can fins what is going on?

**Comment by mymike00** [comment]
Yep, next week I'll do it, but that's odd imho, as I am able to build it fine...

**Comment by dobey** [comment]
> Yep, next week I'll do it, but that's odd imho, as I am able to build it fine...

But are you running the tests as well? The error isn't that building failed, but the tests failed. You need to run `make test` after you've built things.

**Comment by myii** [comment]
@mymike00 The CI build tests have been fixed with #105, so to get the build passing for this PR, you need to rebase on the latest changes in the `xenial` branch and then `git push -f` to trigger another CI build.

**Comment by mymike00** [comment]
there are a lot of failing merge, not sure if I can merge them correctly. at this point, could be easy to pull the latest branch and just apply my changes and make a new pr?

**Comment by myii** [comment]
@mymike00 I just tested rebasing your branch on top of the latest `xenial` branch and it works fine.  You should be able to do something like below, where I'm using `master` to track the main upstream branch and `xenial` to represent this PR branch:

```bash
$ git checkout master
$ git pull
$ git checkout xenial
$ git rebase master
$ git push -f
```

**Comment by mymike00** [comment]
oh, sorry, I was rebasing the master branch. ok but when I push it says I need to pull before because of a conflict, should I just force pushing or pull and resolve it?

**Comment by myii** [comment]
@mymike00 To make this a little easier, could you please give the output of:

```
$ git remote -v; git branch -vv
```

**Comment by mymike00** [comment]
why? it's easy also now. just wondering why did you tell me `git push -f`? why `-f`?
any way, here you go

```
origin	https://github.com/mymike00/system-settings.git (fetch)
origin	https://github.com/mymike00/system-settings.git (push)
ubports	https://github.com/ubports/system-settings.git (fetch)
ubports	https://github.com/ubports/system-settings.git (push)
* xenial dd691f9c [origin/xenial: ahead 54, behind 4] fixed the use of ItemPage where content was hidden under the PageHeader
```

**Comment by myii** [comment]
Fair enough, that works.  The `git push -f` is only for your PR branch if you've rebased it on the main upstream branch.

**Comment by mymike00** [comment]
ok, thanks. but now why it isn't build?

**Comment by myii** [comment]
That's why the `rebase` and `push -f`.  See https://github.com/myii/system-settings/tree/mymike00.  That's what I was leading to for this PR.

**Comment by mymike00** [comment]
I did the rebase but I pulled before pushing to not force the push

**Comment by myii** [comment]
This can still be resolved.  Are you interested or just leave it?  Don't worry, won't do anything to this PR until you are convinced it is OK.

**Comment by mymike00** [comment]
Eh? what should be solved? sure I'm convinced it is ok. this pr is still open only because of failing tests and once fixed them it'll be merged. just need to somehow trigger the CI build to see if test are solved

**Comment by myii** [comment]
Yes, it is OK.  You were asking about the build and I was explaining how I triggered the build.  Never mind.  Just request one of the upstream maintainers and they can run the build.

**Comment by mymike00** [comment]
it still doesn't build, hoe can I solve this? @mariogrip ?

**Comment by myii** [comment]
@mymike00 I tested a dummy PR (#106) with just your 4 commits (not the 59 commits above) but even then the CI build failed.  Someone upstream is going to have to fix that first, it seems.

**Comment by UniversalSuperBox** [comment]
@mymike00, looks like after all this testing, this PR isn't able to be merged cleanly. Can you recreate it in separate PRs, with the pageHeader fixes separate from the rest?

**Pull request closed without merging**
