### PR TITLE
Add support for blue light filter (using red filter overlay)

### PR DESCRIPTION
**Pull request by mariogrip**
This adds support for a overlay based blue light filter

needs red filter overlay patch: https://github.com/ubports/unity8/pull/60

screenshot20180811_025705479

### CODE REVIEW

**Comment by NeoTheThird** [comment]
Are we targeting this for OTA-4?

**Comment by mariogrip** [comment]
@NeoTheThird no, this is for ota5

**Review by UniversalSuperBox — CHANGES_REQUESTED** [review]
The performance of this method is not good enough for use on any device. Installing this slows the framerate considerably.

**Comment by UniversalSuperBox** [comment]
Closing due to poor performance of the blue overlay.

**Pull request closed without merging**
