### PR TITLE
Add More Info to the Reset Page

### PR DESCRIPTION
**Pull request by cibersheep**
~~Don't merge until I can test on a device.~~ Tested. See screenshots below

### CODE REVIEW

**Comment by cibersheep** [comment]
Before / After

imatge imatge

**Comment by dobey** [comment]
Mmm, can you post the screenshots in English instead perhaps, so the widest audience can clearly understand what changed? I guess much of our community don't know Catalan. :)

**Comment by cibersheep** [comment]
True. Sorry.
(It's actually the same text shown in the `Dialog` after tapping on each button)

**Comment by cibersheep** [comment]
Here :)

imatge

**Review by UniversalSuperBox — CHANGES_REQUESTED** [review]
`system-settings` must be rebuilt to update the translation sources. Please let me know if you need help with this.

**Comment by cibersheep** [comment]
Ouh. Nice. I'll try to do that on Monday

**Comment by cibersheep** [comment]
Yep. So, I can't seem to be able to build it (as said in INSTALL).
What do I have to have installed?

PS: Is there a way to update just the pot file?

**Comment by UniversalSuperBox** [comment]
Got it for you. :)

**Review by UniversalSuperBox — APPROVED** [review]

**Pull request merged**
