### PR TITLE
Update some settings pages

### PR DESCRIPTION
**Pull request by mateosalta**
work on some dividers, and usage of SettingsItemTitle

### CODE REVIEW

**Comment by mateosalta** [comment]
@UniversalSuperBox Ok, I think this one is ready - sorry about the noise with the commits, but this now focuses on changing titles to SettingsItemTitle

**Comment by UniversalSuperBox** [comment]
This is the old "Reset devices" page:

reset devices, before changes

And here is the new one:

reset devices, after changes

Is this the change you expected?

**Comment by mateosalta** [comment]
@UniversalSuperBox yes, that is the style of all the system headers, the ones in reset are different and do not match the rest of the app.

We should change the explanation text as well now, I will look into what the rest of the app is using for this to match, after that it should look better together

**Comment by mateosalta** [comment]
That should fix the captions, here is with the new commit:
screenshot20200315_091507681

**Comment by mateosalta** [comment]
I'm not completely sold on the the button usage, but it makes sense in these cases to use a button - although we could use a list item like in wiif's "Connect to hidden network..." hm, let me try that and see how it looks

**Review by J053Fabi0 — DISMISSED** [review]

**Review by mariogrip — DISMISSED** [review]
LGTM :+1:

**Comment by Flohack74** [comment]
@cibersheep anything from your side? =)

**Comment by cibersheep** [comment]
Looks good to me.

@mateosalta I agree about the buttons... I always thought it need some work but I don't know the direction. ¿Full width buttons? Is what we have in the Tethering area, VPN, and when select the current Wi-Fi connection...

**Comment by mymike00** [comment]
Buttons can be removed imho. They don't add any additional info, it's the same text as the title...

I'd remove the buttons and move the `onClicked: {...}` code to the `ListItem`

**Comment by mariogrip** [comment]
> Buttons can be removed imho. They don't add any additional info, it's the same text as the title...
> 
> I'd remove the buttons and move the `onClicked: {...}` code to the `ListItem`

Any progress on this?

**Review by mariogrip — APPROVED** [review]
LGTM :+1:

**Comment by cibersheep** [comment]
Looks good on Arale dev channel 2020-08-27

**Comment by Flohack74** [comment]
Ok so is the intended behaviour now that we have arrows on the list item to indicate that you can click here and then there comes the safety confirmation right?

**Comment by farkasdvd** [comment]
Device: bq e5
Image: 2020-W35/2

After confirming the Reset Launcher dialog the launcher is correctly reset but the System Settings app becomes unresponsive. Restarting the app fixes the issue. I haven't tried the Erase and Reset All option.

**Comment by cibersheep** [comment]
> Ok so is the intended behaviour now that we have arrows on the list item to indicate that you can click here and then there comes the safety confirmation right?

Yep. The ListItem, as stated by Mateo, is more coherent with the rest of the System Settings behaviour

**Comment by jezek** [comment]
> Ok so is the intended behaviour now that we have arrows on the list item to indicate that you can click here and then there comes the safety confirmation right?

Device: FP2
Image: 2020-W35/2

Works as described in quote.

**Comment by cibersheep** [comment]
Works as expected (didn't trigger the resets though) on E5HD RC

**Pull request merged**
