### PR TITLE
Orange to base, remove ListItems

### PR DESCRIPTION
**Pull request by cibersheep**
Date picker changes:
- remove deprecated import
- orange to theme collor

### CODE REVIEW

**Comment by cibersheep** [comment]
(updated with the latest push -- part II)

Before:

imatge

After:

imatge

imatge

**Comment by UniversalSuperBox** [comment]
This still seems a little faint in the dark theme, I'm having difficulty distinguishing it from the background.

**Comment by cibersheep** [comment]
I'll look into it

**Comment by cibersheep** [comment]
Updated. I removed the opacity for the highlight

**Review by UniversalSuperBox — APPROVED** [review]
Great! Visible on both light and dark.

**Pull request merged**
