### PR TITLE
WIP: Update check only

### PR DESCRIPTION
**Pull request by mardy**
Merge #148 first for an easier review.

### CODE REVIEW

**Comment by mariogrip** [comment]
Why are we removing the install of updates feature? Having it in one place is such an amazing user experience, this is something that is quite unique.

**Comment by UniversalSuperBox** [comment]
@mariogrip, relevant discussion:

https://github.com/ubports/ubuntu-touch/issues/1108

https://t.me/ubports_qa_team/14178

**Comment by mardy** [comment]
(marking as WIP until the unit tests are fixed)

**Comment by dobey** [comment]
> (marking as WIP until the unit tests are fixed)

Can you please keep the crossbuilder "fixes" separate from this?

**Comment by mardy** [comment]
> Can you please keep the crossbuilder "fixes" separate from this?

That's #148, please review :-)

**Comment by UniversalSuperBox** [comment]
Superseded by https://github.com/ubports/system-settings/pull/151

**Pull request closed without merging**
